[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "python-jobspy"
version = "1.1.82"
description = "Job scraper for LinkedIn, Indeed, Glassdoor, ZipRecruiter, StepStone & Arbeitsagentur"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Cullen Watson", email = "cullen@cullenwatson.com" },
    { name = "Zachary Hampton", email = "zachary@zacharysproducts.com" },
]
keywords = [
    "jobs-scraper",
    "linkedin",
    "indeed",
    "glassdoor",
    "ziprecruiter",
    "stepstone",
    "arbeitsagentur",
]
dependencies = [
    "requests>=2.32.3",
    "beautifulsoup4>=4.13.3",
    "pandas>=2.2.3",
    "numpy>=2.1.0",
    "pydantic>=2.10.6",
    "tls-client>=1.0.1",
    "markdownify>=1.1.0",
    "regex>=2024.11.6",
    "playwright>=1.50.0",
]

[project.urls]
Homepage = "https://github.com/cullenwatson/JobSpy"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "black>=24.10.0",
    "pre-commit>=4.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["jobspy"]

[tool.black]
line-length = 88
